Bidme/Bidme.MVC.Web/Controllers/CompraController.cs
using Bidme.Dominio.Models;
using Bidme.MVC.Web.ViewModels;
using Bidme.Persistencia.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Bidme.MVC.Web.Controllers
{
    [Authorize]
    public class CompraController : Controller
    {        
        #region FIELDs
        private UnitOfWork _unit = new UnitOfWork();
        #endregion

        #region GETs
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Comprar(string idUser)
        {
            if (idUser == null)
            {
                string userId = User.Identity.GetUserId();
                if(userId != null)
                {
                    idUser = userId;
                }
                else
                {
                    //se não estiver logado, mostrar todos os produtos disponiveis para compra que estão válidos
                    //negociacoes filtradas validas
                    var negocios = _unit.NegociacaoRepository.BuscarPor(n => n.ValidadeNegociacao.ValidadeDias > 0);                   
                    var mV = new NegociacaoViewModel()
                    {
                        Negociacoes = negocios
                    };

                    return View(mV);
                }                
            }
            ICollection<Negociacao> negociacoes = ListarNegociacoes(idUser);
            var c = _unit.CreditoRepository.BuscarPor(cP => cP.Pessoa.IdUser == idUser);
            var creditos = new CreditoViewModel()
            {
                Creditos = c
            };
            var model = new NegociacaoViewModel()
            {
                Negociacoes = negociacoes,
                Creditos = creditos
            };
            return View(model);
        }

        //método para buscar negociações na tela de compra
        [HttpGet]
        public ActionResult BuscarProduto(string nome, string idUser)
        {            
            if (nome == "")
            {
                var negociacoes = _unit.NegociacaoRepository
                    .BuscarPor(n => n.IdComprador == null, n=>n.IdVendedor != idUser)
                    .Where(n=>n.Tipo == 1)
                    .ToList();
                return PartialView("_tabelaProdutosDisponiveis", negociacoes);
            }                     
            var negociacoesComNome = _unit.NegociacaoRepository.BuscarPor(n => n.Produto.Nome == nome, n => n.IdComprador == null)
                .Where(n=>n.Tipo == 1).Where(n=>n.IdVendedor != idUser).ToList();
            return PartialView("_tabelaProdutosDisponiveis", negociacoesComNome);
        }

        [HttpGet]
        public ActionResult VisualizarProduto(int IdProduto)
        {
            return View();
        }
        #endregion

        #region POSTs
        [HttpPost]
        public ActionResult Comprar(NegociacaoViewModel model)
        {
            //verificar créditos
            //subtrair crédito do total atual
            //calcular valor de acordo com a quantidade de créditos utilizados
            //inserir valor calcular na negociacao
            //atualizar tabela de creditos
            //atualizar tabela de negociacao (valor)
            if (!ModelState.IsValid)
            {
                return View();
            }

            var negociacao = _unit.NegociacaoRepository.BuscarPorId(model.Id);
            var comprador = _unit.PessoaRepository.BuscarPor(p => p.IdUser == model.IdUser).First();            

            negociacao.IdComprador = comprador.IdUser;
            negociacao.Status = model.Status;
            negociacao.Valor = model.Valor;
            //Data em que foi dada a proposta
            negociacao.Data = DateTime.Now;
            negociacao.Tipo = 1;

            _unit.NegociacaoRepository.Alterar(negociacao);
            _unit.Salvar();

            return RedirectToAction("Index", "Painel", new { idUser = model.IdUser });
        }
        #endregion

        #region PRIVATEs
        private ICollection<Negociacao> ListarNegociacoes(string idUser)
        {
            return _unit.NegociacaoRepository.BuscarPor(n => n.IdVendedor != idUser, n => n.Tipo == 1)
                .Where(n => n.IdComprador == null)
                .Where(n=>n.ValidadeNegociacao.ValidadeDias > 0)
                .ToList();
        }

        #endregion
    }
}

Bidme/Bidme.MVC.Web/Views/Compra/Comprar.cshtml
@model Bidme.MVC.Web.ViewModels.NegociacaoViewModel
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Comprar";
}
<hr />
<div class="row">
    <div class="col-md-4 col-sm-4"></div>
    @using (Ajax.BeginForm("BuscarProduto", null,
        new AjaxOptions { HttpMethod="get", UpdateTargetId="thumbs", InsertionMode = InsertionMode.Replace},
        new { id="formBuscaProduto" }))
    {
        <input type="hidden" name="IdUser" id="IdUser" value="@User.Identity.GetUserId()" />

        <div class="col-md-5 col-sm-5">
            <input type="text" id="Nome" name="Nome" class="form-control" placeholder="Buscar Produto" />            
        </div>

        <div class="col-md-1 col-sm-1">
            <input type="submit" value="Buscar" class="btn btn-info btn-sm" />
        </div>
    }
    <div class="col-md-2 col-sm-2"></div>
</div>

<hr />

@Html.Partial("_tabelaProdutosDisponiveis", Model.Negociacoes)

<!--Modal -->
<div class="modal" id="ModalComprar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proposta de Compra</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Comprar", "Compra", FormMethod.Post))
                {
                    <input type="hidden" name="Id" id="Id" />
                    @Html.HiddenFor(n => n.IdUser, new { @Value = User.Identity.GetUserId() })
                    @Html.HiddenFor(n => n.Status, new { @Value = "Em andamento" })
                    <div class="form-group">
                        
                        @Html.Label("Valor do Produto")
                        @Html.TextBoxFor(n => n.Produto.Valor, new { @class = "form-control", disabled = "disabled" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Sua Oferta em Diamantes")
                        @Html.TextBoxFor(n=>n.Diamantes,
                       new
                       {
                           @class = "form-control",
                           @type = "number",
                           @step = "1",
                           @min = "10",
                           @max = Model.Creditos.Creditos.Last().Total,
                           @Value = "10"
                       })                       
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-sm" value="Enviar" />
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script type="text/javascript">
        $().ready(function () {
            console.log("ok"); //it shows this message
            $("#thumb").on('click', function () {
                $("#btnProposta").click();
            });

        });

        function setFormValues(vals) {
            var valor = parseFloat(vals[1]);
            $("#Id").val(vals[0]);
            $("#Produto_Valor").val(vals[1]);
            $("#Valor").val(valor - (valor * 0.10));
            console.log("Valor=" + valor + " Calculo=" + (valor - (valor * 0.10)));
        }
    </script>
}

Bidme/Bidme.MVC.Web/Views/Compra/_tabelaProdutosDisponiveis.cshtml
@model List<Bidme.Dominio.Models.Negociacao>

<div class="row" id="thumbs">
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-sm-2">
            <div class="thumbnail" id="thumb">
                <img src="@item.Produto.Imagem" alt="@item.Produto.Nome" style="min-height:120px;height:120px;" />
                <div class="caption">
                    <h4 style="text-align:center">@item.Produto.Nome</h4>
                    <p style="text-align:center">
                    @*verificar se possui algum lance dado pelo valor, mudar para controller fazer isso*@
                    @if (item.Valor == 0)
                    {
                        @: R$ @item.Produto.Valor
                    }else
                    {
                        @: R$ @item.Valor
                    }
                    </p>
                    <p style="text-align:center"> Restam @item.ValidadeNegociacao.ValidadeDias dia(s)!</p>
                    <p style="text-align:center">
                        <script>
                            var valores = ["@item.Id", "@item.Produto.Valor"];
                        </script>
                        <button onclick="setFormValues(valores)" id="btnProposta" class="btn btn-success btn-sm" data-toggle="modal" data-target="#ModalComprar">
                            Eu Quero!
                        </button>
                    </p>
                </div>
            </div>
        </div>
    }
</div>